[tool.poetry]
name = "09-web-hw-2"
version = "0.1.0"
description = ""
authors = ["OleksiyM <OleksiyM@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Scrapy = "^2.11.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
